# Generated by Django 5.1.3 on 2024-12-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='codigo_postal',
            field=models.CharField(default='codigo postal', max_length=5),
        ),
    ]
